[kbmod_ml]
# The file name of the true positive samples
true_positive_file_name = 'true_positive_stamps_full.npy'

# The file name of the false positive samples
false_positive_file_name = 'false_positive_stamps_trimmed.npy'
